# Generated by Django 6.0.5 on 2026-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Workpaces_name', models.CharField()),
                ('nicho', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
