# Generated by Django 6.0.5 on 2026-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_etapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='contatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
