# Generated by Django 6.0.5 on 2026-05-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_contatos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contatos',
            new_name='canais',
        ),
    ]
