# Generated by Django 6.0.5 on 2026-06-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_lead_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agente_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
