# Generated by Django 6.0.5 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_workspace_agente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agente_instrucoes',
            field=models.TextField(blank=True, default='Você é um assistente de prospecção do Dalle Piagge Ladrilhos. Responda de forma clara e objetiva.'),
        ),
    ]
