# Generated by Django 6.0.5 on 2026-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_workspace_agente_instrucoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agente_nome',
            field=models.CharField(default='Agente IA Assistente', max_length=255),
        ),
    ]
