# Generated by Django 6.0.5 on 2026-06-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_workspace_agente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConhecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='conhecimento/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conhecimentos', to='cadastro.workspace')),
            ],
        ),
    ]
