# Generated by Django 6.0.5 on 2026-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_documentoconhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
