# Generated by Django 6.0.5 on 2026-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_lead_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canais',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
